name: BuildTest
on:
  push:
    branches:
      - main
      - 128-321-fix-af-deploy-artifact-issue-fra-buildtest-workflow
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Running pytest
      run: |
        pytest tests/ --cov=hello_app --cov-report=xml --cov-report=html --disable-warnings
    # kører pylint og threshold er sat til 5.0 (for ikke at fejl for meget i første omgang, inden vi får rettet alle issues)
    - name: Analysing the code with pylint 
      continue-on-error: true
      run: |
       pylint --max-line-length=128 hello_app tests > tests/pylint_report.txt

    - name: Check Pylint score
      run: |
        score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' tests/pylint_report.txt)
        echo "Pylint score: $score"
        python -c "import sys; sys.exit(0 if $score >= 5.0 else 1)" 

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          release.zip
          !venv/