name: Deploy Python app to Azure

on:
  workflow_run:
    workflows: [BuildTest]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: python-app
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GIT_TOKEN }} # Needed to download the artifact, cause else its scoped
          
      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'agil-noteprojekt'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C2E173D2E91D4DDBABCEAFA105B370E9 }}
