name: TestCoverage

on:
  push:
    branches:
      - 96-32-test-coverage-overblik--sonarcloud

  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Running pytest
      run: |
        pytest tests/ --cov=hello_app --cov-report=xml --cov-report=html --disable-warnings

    - name: Analysing the code with pylint
      continue-on-error: true
      run: |
       pylint hello_app > pylint_report.txt


    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: hello_app
        args: >
          -Dsonar.projectKey=PBI22_Agil-Flask-Note-Projekt
          -Dsonar.organization=pbi22
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.python.coverage.reportPaths=/github/workspace/hello_app/coverage.xml
          -Dsonar.python.pylint.reportPaths=/github/workspace/hello_app/pylint_report.txt